name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    continue-on-error: true
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2


    - name: git clone & make list
      run: |
        git clone https://github.com/uhug/uhug.github.io.git
        cd uhug.github.io
        date '+%Y%m%d%H%M%S' > ./uhug.github.io/_docs/dummy
        

    - name: Deploy build
      run: |
        git config --local user.email "uhug@naver.com"
        git config --local user.name "DokySp"
        git add .
        git status
        git commit -am "Triggered by acmicpc-practice in `date -d'9 hour' '+%Y.%m.%d-%H:%M:%S'`"


    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
