name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    continue-on-error: true
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2


    - name: git clone & make list
      run: |
        git clone --depth 1 https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/uhug/uhug.github.io.git
        pwd
        ls
        cd uhug.github.io
        date '+%Y%m%d%H%M%S' > ./_docs/dummy
        

    - name: Deploy build
      run: |
        cd uhug.github.io
        pwd
        ls
        git config --local user.email "uhug@naver.com"
        git config --local user.name "DokySp"
        git add .
        git status
        git commit -am "Triggered by acmicpc-practice in `date -d'9 hour' '+%Y.%m.%d-%H:%M:%S'`"

    - name: Push changes
      run: | 
        cd uhug.github.io
        pwd
        ls
        git status
        git push
        
      
